services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: trender
      MYSQL_DATABASE: trender
    ports:
      - "3307:3306"
    volumes:
      - trender_mysql:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"

volumes:
  trender_mysql:
